name: Publish to pub.dev

on:
  push:
    branches:
      - main

jobs:
  publish:
    if: "${{ contains(github.event.head_commit.message, 'chore(main): release') }}"
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1