name: Publish to pub.dev

on:
  push:
    branches:
      - main

jobs:
  publish:
    if: "${{ contains(github.event.head_commit.message, 'chore(main): release') }}"
    permissions:
      id-token: write

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
  
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.6'
          channel: stable
    
      - name: Install Dependencies
        run: flutter pub get

      - name: Check Publish Warnings
        run: dart pub publish --dry-run
        
      - name: Publish
        uses: k-paxian/dart-package-publisher@v1.5.1
        with:
          credentialJson: ${{ secrets.CREDENTIAL_JSON }}
          flutter: true
          skipTests: true